export const images = {
  landscape: [
    {
      id: 1,
      section: "Landscape",
      pic: "img/lge/landscape/DJI_0006.jpg",
      alt: "Redhook, Brooklyn",
      caption: "The abandonded silo. Red Hook, Brooklyn",
    },
    {
      id: 2,
      section: "Landscape",
      pic: "img/lge/landscape/DJI_0059.jpg",
      alt: "Bruno Trucking sign. Gowanus, Brooklyn",
      caption: "Bruno Trucking Sales sign. Gowanus, Brooklyn",
    },
    {
      id: 3,
      section: "Landscape",
      pic: "img/lge/landscape/vanpac02.jpg",
      alt: "Vanderbilt and Pacific Brooklyn, NY",
      caption:
        "This no longer exists, a story of gentrification. Prospect Heights, Brooklyn",
    },
    {
      id: 4,
      section: "Landscape",
      pic: "img/lge/landscape/TOTR_Sunset.jpg",
      alt: "Southern view from Top of the Rock, NYC",
      caption: "View from the Top of the Rock. Rockefeller Center, NYC",
    },
    {
      id: 5,
      section: "Landscape",
      pic: "img/lge/landscape/5points.jpg",
      alt: "5points Queens, NY",
      caption:
        "This no longer exists, a story of gentrification. 5Pointz, Long Island City Queens, NY for: Vice Magazine",
    },
    {
      id: 6,
      section: "Landscape",
      pic: "img/lge/landscape/DJI_0075.jpg",
      alt: "Brooklyn Navy Yard solar project from above",
      caption: "Brooklyn Navy Yard Solar system built by: Solar Energy Systems",
    },
    {
      id: 7,
      section: "Landscape",
      pic: "img/lge/landscape/AviatorColor.jpg",
      alt: "Aviator rink Brooklyn, NY",
      caption: "Aviator Sports Center. Floyd Bennett Field, Brooklyn",
    },
    {
      id: 8,
      section: "Landscape",
      pic: "img/lge/landscape/Charlie.jpg",
      alt: "Hiking in the White Mountain range",
      caption: "Foggy Morning, White Mountain National Forest",
    },
    {
      id: 9,
      section: "Landscape",
      pic: "img/lge/landscape/larahotrock.jpg",
      alt: "Sunbather, Antigua, W.I.",
      caption: "Sunbathing on the hot rock. Antigua W.I.",
    },
    {
      id: 10,
      section: "Landscape",
      pic: "img/lge/landscape/oia2.jpg",
      alt: "Oia SanTorini, Greece",
      caption: "Sunset in Oia. San Torini, Greece",
    },
    {
      id: 11,
      section: "Landscape",
      pic: "img/lge/landscape/hfscrowd.jpg",
      alt: "HFStival front row",
      caption:
        "All access pass, a view from the stage. WHFStival, RFK Stadium Washington D.C.",
    },
  ],
  stills: [
    {
      id: 1,
      section: "Still Life",
      pic: "img/lge/still/Interview_Handbags.jpg",
      alt: "Handbags, Interview Magazine",
      caption: "Interview Magazine: Handbags",
    },
    {
      id: 2,
      section: "Still Life",
      pic: "img/lge/still/SnakeBag.jpg",
      alt: "gucci bag",
      caption: "Interview Magazine: Gucci Snakeskin bag",
    },
    {
      id: 3,
      section: "Still Life",
      pic: "img/lge/still/Interview_Watch.jpg",
      alt: "Watch mantage",
      caption: "Interview Magazine: Fendi Watch montage",
    },
    {
      id: 4,
      section: "Still Life",
      pic: "img/lge/still/Technomarine.jpg",
      alt: "Technomarine watch",
      caption: "Interview Magazine: Technomarine watch",
    },
    {
      id: 5,
      section: "Still Life",
      pic: "img/lge/still/TechnomarineRGO.jpg",
      alt: "Technomarine watches",
      caption: "Interview Magazine: Technomarine watches",
    },
    {
      id: 6,
      section: "Still Life",
      pic: "img/lge/still/Magaschoni_Bag.jpg",
      alt: "Magaschoni_Bag",
      caption: "Magaschoni Bags Summer ad",
    },
    {
      id: 7,
      section: "Still Life",
      pic: "img/lge/still/Interview_Perfume.jpg",
      alt: "M/Mink Parfum bottle",
      caption: "Interview Magazine: M/Mink Parfum",
    },
    {
      id: 8,
      section: "Still Life",
      pic: "img/lge/still/Dior.jpg",
      alt: "Dior Handbag",
      caption: "Baron & Baron, Miss Dior B-Roll",
    },
    {
      id: 9,
      section: "Still Life",
      pic: "img/lge/still/cotica02.jpg",
      alt: "Cotica Jewelry",
      caption: "Cotica Jewelry LookBook",
    },
    {
      id: 10,
      section: "Still Life",
      pic: "img/lge/still/Burberry_18.jpg",
      alt: "Burberry perfume bottle",
      caption: "Interview Magazine: Burberry perfume",
    },
    {
      id: 11,
      section: "Still Life",
      pic: "img/lge/still/Lexuschassis.jpg",
      alt: "Lexus chassis",
      caption: "Lexus Magazine: Making a race car",
    },
  ],
};
